//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2CDevSync.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://login.microsoftonline.com/{0}")]
        public string AADAuthority {
            get {
                return ((string)(this["AADAuthority"]));
            }
            set {
                this["AADAuthority"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://graph.microsoft.com/beta/trustFramework/policies/{0}")]
        public string B2BApi {
            get {
                return ((string)(this["B2BApi"]));
            }
            set {
                this["B2BApi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("79ce0569-549a-46d5-b98b-b0e9c8f04f25")]
        public string SyncAppId {
            get {
                return ((string)(this["SyncAppId"]));
            }
            set {
                this["SyncAppId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("hackerdemob2c.onmicrosoft.com")]
        public string B2CTenant {
            get {
                return ((string)(this["B2CTenant"]));
            }
            set {
                this["B2CTenant"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Configured {
            get {
                return ((bool)(this["Configured"]));
            }
            set {
                this["Configured"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://B2CSyncApp")]
        public string RedirectUri {
            get {
                return ((string)(this["RedirectUri"]));
            }
            set {
                this["RedirectUri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public string PopupDuration {
            get {
                return ((string)(this["PopupDuration"]));
            }
            set {
                this["PopupDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DefaultEndpointsProtocol=https;AccountName=wutnu;AccountKey=uGIK+v15U3UWl3PvDr9px" +
            "w8higNxCXW2UBtJZ4hykWOPZy1I3dNO/iN2PKODuDyJj5yfZPLsJaUXdq/G81oPJQ==;EndpointSuff" +
            "ix=core.windows.net")]
        public string StorageConnectionString {
            get {
                return ((string)(this["StorageConnectionString"]));
            }
            set {
                this["StorageConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("b2c")]
        public string StorageContainerName {
            get {
                return ((string)(this["StorageContainerName"]));
            }
            set {
                this["StorageContainerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string SyncStorageBool {
            get {
                return ((string)(this["SyncStorageBool"]));
            }
            set {
                this["SyncStorageBool"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\brhacke\\OneDrive\\Dev\\B2CFramework\\New\\UI")]
        public string UIPath {
            get {
                return ((string)(this["UIPath"]));
            }
            set {
                this["UIPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\brhacke\\OneDrive\\Dev\\B2CFramework\\New")]
        public string PolicyPath {
            get {
                return ((string)(this["PolicyPath"]));
            }
            set {
                this["PolicyPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string SyncPolicyBool {
            get {
                return ((string)(this["SyncPolicyBool"]));
            }
            set {
                this["SyncPolicyBool"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<SyncProfiles xmlns:xsi=\"http://www.w3.o" +
            "rg/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <Pr" +
            "ofiles>\r\n    <SyncProfile>\r\n      <SyncProfileName>Unified-HackerDemo</SyncProfi" +
            "leName>\r\n      <StorageConnectionString>DefaultEndpointsProtocol=https;AccountNa" +
            "me=wutnu;AccountKey=uGIK+v15U3UWl3PvDr9pxw8higNxCXW2UBtJZ4hykWOPZy1I3dNO/iN2PKOD" +
            "uDyJj5yfZPLsJaUXdq/G81oPJQ==;EndpointSuffix=core.windows.net</StorageConnectionS" +
            "tring>\r\n      <StorageContainerName>b2c</StorageContainerName>\r\n      <SyncStora" +
            "geBool>true</SyncStorageBool>\r\n      <SyncPolicyBool>true</SyncPolicyBool>\r\n    " +
            "  <UIPath>C:\\Users\\brhacke\\OneDrive\\Dev\\MSFT\\B2C-IEF-hackerdemob2c\\UI</UIPath>\r\n" +
            "      <SyncRecursive>true</SyncRecursive>\r\n      <PolicyPath>C:\\Users\\brhacke\\On" +
            "eDrive\\Dev\\MSFT\\B2C-IEF-hackerdemob2c\\Policies</PolicyPath>\r\n    </SyncProfile>\r" +
            "\n    <SyncProfile>\r\n      <SyncProfileName>Tunamatic</SyncProfileName>\r\n      <S" +
            "torageConnectionString>DefaultEndpointsProtocol=https;AccountName=kaas2;AccountK" +
            "ey=j41ZoNYssEJneqQ1k063eIMl3t6vuEV0e+vtbimpqp7xTVc9qG3Bb65jWd9EACp5QqGqi9P8oY3Cz" +
            "UUA/RZ/0w==;EndpointSuffix=core.windows.net</StorageConnectionString>\r\n      <St" +
            "orageContainerName>auth</StorageContainerName>\r\n      <SyncStorageBool>true</Syn" +
            "cStorageBool>\r\n      <SyncPolicyBool>false</SyncPolicyBool>\r\n      <UIPath>C:\\Us" +
            "ers\\brhacke\\OneDrive\\Dev\\Tunamatic\\Tunamaticauth</UIPath>\r\n      <SyncRecursive>" +
            "true</SyncRecursive>\r\n      <PolicyPath />\r\n    </SyncProfile>\r\n    <SyncProfile" +
            ">\r\n      <SyncProfileName>HackerdemoB2C native UI only</SyncProfileName>\r\n      " +
            "<StorageConnectionString>DefaultEndpointsProtocol=https;AccountName=wutnu;Accoun" +
            "tKey=uGIK+v15U3UWl3PvDr9pxw8higNxCXW2UBtJZ4hykWOPZy1I3dNO/iN2PKODuDyJj5yfZPLsJaU" +
            "Xdq/G81oPJQ==;EndpointSuffix=core.windows.net</StorageConnectionString>\r\n      <" +
            "StorageContainerName>b2cstock</StorageContainerName>\r\n      <SyncStorageBool>tru" +
            "e</SyncStorageBool>\r\n      <SyncPolicyBool>false</SyncPolicyBool>\r\n      <UIPath" +
            ">C:\\Users\\brhacke\\OneDrive\\Dev\\B2CFramework\\b2cStock</UIPath>\r\n      <SyncRecurs" +
            "ive>true</SyncRecursive>\r\n      <PolicyPath />\r\n    </SyncProfile>\r\n    <SyncPro" +
            "file>\r\n      <SyncProfileName>Vue Demo</SyncProfileName>\r\n      <StorageConnecti" +
            "onString>DefaultEndpointsProtocol=https;AccountName=vuedemo;AccountKey=HdvUv+7P7" +
            "GhlUSNyYjuGbUnPuvlLSS6DNRIBlAU3uewMpl6U23qKuU+o5eqmmataLWBDpLCB4hqNv/d3g44s8Q==;" +
            "EndpointSuffix=core.windows.net</StorageConnectionString>\r\n      <StorageContain" +
            "erName>$web</StorageContainerName>\r\n      <SyncStorageBool>true</SyncStorageBool" +
            ">\r\n      <SyncPolicyBool>false</SyncPolicyBool>\r\n      <UIPath>C:\\Users\\brhacke\\" +
            "OneDrive\\Dev\\MSFT\\adaljs sample</UIPath>\r\n      <SyncRecursive>true</SyncRecursi" +
            "ve>\r\n      <PolicyPath />\r\n    </SyncProfile>\r\n    <SyncProfile>\r\n      <SyncPro" +
            "fileName>West Bend UI PoC</SyncProfileName>\r\n      <StorageConnectionString>Defa" +
            "ultEndpointsProtocol=https;AccountName=wutnu;AccountKey=uGIK+v15U3UWl3PvDr9pxw8h" +
            "igNxCXW2UBtJZ4hykWOPZy1I3dNO/iN2PKODuDyJj5yfZPLsJaUXdq/G81oPJQ==;EndpointSuffix=" +
            "core.windows.net</StorageConnectionString>\r\n      <StorageContainerName>pocwbui<" +
            "/StorageContainerName>\r\n      <SyncStorageBool>true</SyncStorageBool>\r\n      <Sy" +
            "ncPolicyBool>false</SyncPolicyBool>\r\n      <UIPath>C:\\Users\\brhacke\\OneDrive - M" +
            "icrosoft\\Customers\\West Bend\\B2CUI</UIPath>\r\n      <SyncRecursive>true</SyncRecu" +
            "rsive>\r\n      <PolicyPath />\r\n    </SyncProfile>\r\n    <SyncProfile>\r\n      <Sync" +
            "ProfileName>mobiledemo</SyncProfileName>\r\n      <StorageConnectionString>Default" +
            "EndpointsProtocol=https;AccountName=wutnu;AccountKey=uGIK+v15U3UWl3PvDr9pxw8higN" +
            "xCXW2UBtJZ4hykWOPZy1I3dNO/iN2PKODuDyJj5yfZPLsJaUXdq/G81oPJQ==;EndpointSuffix=cor" +
            "e.windows.net</StorageConnectionString>\r\n      <StorageContainerName>mobiletest<" +
            "/StorageContainerName>\r\n      <SyncStorageBool>true</SyncStorageBool>\r\n      <Sy" +
            "ncPolicyBool>false</SyncPolicyBool>\r\n      <UIPath>C:\\Users\\brhacke\\OneDrive\\Dev" +
            "\\MSFT\\B2C-mobileUI-hackerdemob2c\\UI</UIPath>\r\n      <SyncRecursive>true</SyncRec" +
            "ursive>\r\n      <PolicyPath />\r\n    </SyncProfile>\r\n    <SyncProfile>\r\n      <Syn" +
            "cProfileName>CBPOC Model</SyncProfileName>\r\n      <StorageConnectionString>Defau" +
            "ltEndpointsProtocol=https;AccountName=cbpocmodel;AccountKey=E7jz6F/kY+sNRl2HBsXk" +
            "e1OBJOA3N39L7lX8pVZo9swpqtVCK3vYGvKbJ2byP8aB/9NaljeusdBKC0JBE8lsLg==;BlobEndpoin" +
            "t=https://cbpocmodel.blob.core.windows.net/;QueueEndpoint=https://cbpocmodel.que" +
            "ue.core.windows.net/;TableEndpoint=https://cbpocmodel.table.core.windows.net/;Fi" +
            "leEndpoint=https://cbpocmodel.file.core.windows.net/;</StorageConnectionString>\r" +
            "\n      <StorageContainerName>b2cui</StorageContainerName>\r\n      <SyncStorageBoo" +
            "l>true</SyncStorageBool>\r\n      <SyncPolicyBool>true</SyncPolicyBool>\r\n      <UI" +
            "Path>C:\\Users\\brhacke\\OneDrive - Microsoft\\Customers\\College Board\\UI</UIPath>\r\n" +
            "      <SyncRecursive>true</SyncRecursive>\r\n      <PolicyPath>C:\\Users\\brhacke\\On" +
            "eDrive - Microsoft\\Customers\\College Board\\mfapolicies</PolicyPath>\r\n    </SyncP" +
            "rofile>\r\n    <SyncProfile>\r\n      <SyncProfileName>UnifiedNew-HackerDemo</SyncPr" +
            "ofileName>\r\n      <StorageConnectionString>DefaultEndpointsProtocol=https;Accoun" +
            "tName=wutnu;AccountKey=uGIK+v15U3UWl3PvDr9pxw8higNxCXW2UBtJZ4hykWOPZy1I3dNO/iN2P" +
            "KODuDyJj5yfZPLsJaUXdq/G81oPJQ==;EndpointSuffix=core.windows.net</StorageConnecti" +
            "onString>\r\n      <StorageContainerName>b2c</StorageContainerName>\r\n      <SyncSt" +
            "orageBool>true</SyncStorageBool>\r\n      <SyncPolicyBool>true</SyncPolicyBool>\r\n " +
            "     <UIPath>C:\\Users\\brhacke\\OneDrive\\Dev\\MSFT\\B2C-IEF-hackerdemob2c\\UI</UIPath" +
            ">\r\n      <SyncRecursive>true</SyncRecursive>\r\n      <PolicyPath>C:\\Users\\brhacke" +
            "\\OneDrive\\Dev\\MSFT\\B2C-IEF-hackerdemob2c\\NewPolicies</PolicyPath>\r\n    </SyncPro" +
            "file>\r\n  </Profiles>\r\n</SyncProfiles>")]
        public global::B2CDevSync.Models.SyncProfiles SyncProfiles {
            get {
                return ((global::B2CDevSync.Models.SyncProfiles)(this["SyncProfiles"]));
            }
            set {
                this["SyncProfiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string OverwritePoliciesBool {
            get {
                return ((string)(this["OverwritePoliciesBool"]));
            }
            set {
                this["OverwritePoliciesBool"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FacebookAppId {
            get {
                return ((string)(this["FacebookAppId"]));
            }
            set {
                this["FacebookAppId"] = value;
            }
        }
    }
}
